// <auto-generated />
using System;
using HotelReservation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelReservation.Migrations
{
    [DbContext(typeof(HotelReservationContext))]
    [Migration("20220411031735_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelReservation.Models.MealRates", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<int>("HighSeasonRate");

                    b.Property<int>("LowSeasonRate");

                    b.Property<string>("MealPlan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("MealRates");
                });

            modelBuilder.Entity("HotelReservation.Models.RoomRates", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("date");

                    b.Property<int>("RatePerRoom");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("RoomRates");
                });

            modelBuilder.Entity("HotelReservation.Models.Rooms", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsReserved");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 3,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 4,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 5,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 6,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 7,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 8,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 9,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 10,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 11,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 12,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 13,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 14,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 15,
                            IsReserved = false,
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = 16,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 17,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 18,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 19,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 20,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 21,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 22,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 23,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 24,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 25,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 26,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 27,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 28,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 29,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 30,
                            IsReserved = false,
                            RoomType = "SeaView"
                        },
                        new
                        {
                            Id = 31,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 32,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 33,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 34,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 35,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 36,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 37,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 38,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 39,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 40,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 41,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 42,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 43,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 44,
                            IsReserved = false,
                            RoomType = "PoolView"
                        },
                        new
                        {
                            Id = 45,
                            IsReserved = false,
                            RoomType = "PoolView"
                        });
                });

            modelBuilder.Entity("HotelReservation.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<int?>("Age");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool?>("Gender");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("RoomId")
                        .HasColumnName("RoomID");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HotelReservation.Models.Users", b =>
                {
                    b.HasOne("HotelReservation.Models.Rooms", "Room")
                        .WithMany("Users")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Users_Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
